//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unify.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("172, 14, 14")]
        public global::System.Drawing.Color General_AccentColour {
            get {
                return ((global::System.Drawing.Color)(this["General_AccentColour"]));
            }
            set {
                this["General_AccentColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool General_AutoColour {
            get {
                return ((bool)(this["General_AutoColour"]));
            }
            set {
                this["General_AutoColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool General_HighContrastText {
            get {
                return ((bool)(this["General_HighContrastText"]));
            }
            set {
                this["General_HighContrastText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Path_ModsDirectory {
            get {
                return ((string)(this["Path_ModsDirectory"]));
            }
            set {
                this["Path_ModsDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool General_Mods_Priority {
            get {
                return ((bool)(this["General_Mods_Priority"]));
            }
            set {
                this["General_Mods_Priority"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Path_GameExecutable {
            get {
                return ((string)(this["Path_GameExecutable"]));
            }
            set {
                this["Path_GameExecutable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool General_Debug {
            get {
                return ((bool)(this["General_Debug"]));
            }
            set {
                this["General_Debug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Path_EmulatorDirectory {
            get {
                return ((string)(this["Path_EmulatorDirectory"]));
            }
            set {
                this["Path_EmulatorDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Path_SaveData {
            get {
                return ((string)(this["Path_SaveData"]));
            }
            set {
                this["Path_SaveData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Emulator_API {
            get {
                return ((int)(this["Emulator_API"]));
            }
            set {
                this["Emulator_API"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Emulator_VerticalSync {
            get {
                return ((bool)(this["Emulator_VerticalSync"]));
            }
            set {
                this["Emulator_VerticalSync"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Emulator_Gamma {
            get {
                return ((bool)(this["Emulator_Gamma"]));
            }
            set {
                this["Emulator_Gamma"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Emulator_Fullscreen {
            get {
                return ((bool)(this["Emulator_Fullscreen"]));
            }
            set {
                this["Emulator_Fullscreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Emulator_DiscordRPC {
            get {
                return ((bool)(this["Emulator_DiscordRPC"]));
            }
            set {
                this["Emulator_DiscordRPC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool General_SaveFileRedirection {
            get {
                return ((bool)(this["General_SaveFileRedirection"]));
            }
            set {
                this["General_SaveFileRedirection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool General_CheckUpdatesOnLaunch {
            get {
                return ((bool)(this["General_CheckUpdatesOnLaunch"]));
            }
            set {
                this["General_CheckUpdatesOnLaunch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long General_LastSoftwareUpdate {
            get {
                return ((long)(this["General_LastSoftwareUpdate"]));
            }
            set {
                this["General_LastSoftwareUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool General_LaunchEmulator {
            get {
                return ((bool)(this["General_LaunchEmulator"]));
            }
            set {
                this["General_LaunchEmulator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long General_LastModUpdate {
            get {
                return ((long)(this["General_LastModUpdate"]));
            }
            set {
                this["General_LastModUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long General_LastPatchUpdate {
            get {
                return ((long)(this["General_LastPatchUpdate"]));
            }
            set {
                this["General_LastPatchUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool General_FirstLaunch {
            get {
                return ((bool)(this["General_FirstLaunch"]));
            }
            set {
                this["General_FirstLaunch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Tweak_Renderer {
            get {
                return ((int)(this["Tweak_Renderer"]));
            }
            set {
                this["Tweak_Renderer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Tweak_Reflections {
            get {
                return ((int)(this["Tweak_Reflections"]));
            }
            set {
                this["Tweak_Reflections"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Tweak_AntiAliasing {
            get {
                return ((int)(this["Tweak_AntiAliasing"]));
            }
            set {
                this["Tweak_AntiAliasing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Tweak_ForceMSAA {
            get {
                return ((bool)(this["Tweak_ForceMSAA"]));
            }
            set {
                this["Tweak_ForceMSAA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Tweak_CameraType {
            get {
                return ((int)(this["Tweak_CameraType"]));
            }
            set {
                this["Tweak_CameraType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("650")]
        public decimal Tweak_CameraDistance {
            get {
                return ((decimal)(this["Tweak_CameraDistance"]));
            }
            set {
                this["Tweak_CameraDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70.0")]
        public decimal Tweak_CameraHeight {
            get {
                return ((decimal)(this["Tweak_CameraHeight"]));
            }
            set {
                this["Tweak_CameraHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.785398185253143")]
        public decimal Tweak_FieldOfView {
            get {
                return ((decimal)(this["Tweak_FieldOfView"]));
            }
            set {
                this["Tweak_FieldOfView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50.0")]
        public decimal Tweak_AmyHammerRange {
            get {
                return ((decimal)(this["Tweak_AmyHammerRange"]));
            }
            set {
                this["Tweak_AmyHammerRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool General_AutoUninstall {
            get {
                return ((bool)(this["General_AutoUninstall"]));
            }
            set {
                this["General_AutoUninstall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Emulator_UserLanguage {
            get {
                return ((int)(this["Emulator_UserLanguage"]));
            }
            set {
                this["Emulator_UserLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emulator_Arguments {
            get {
                return ((string)(this["Emulator_Arguments"]));
            }
            set {
                this["Emulator_Arguments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Tweak_BeginWithRings {
            get {
                return ((decimal)(this["Tweak_BeginWithRings"]));
            }
            set {
                this["Tweak_BeginWithRings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Debug_AllowModStacking {
            get {
                return ((bool)(this["Debug_AllowModStacking"]));
            }
            set {
                this["Debug_AllowModStacking"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool General_Patches_Priority {
            get {
                return ((bool)(this["General_Patches_Priority"]));
            }
            set {
                this["General_Patches_Priority"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string General_Profile {
            get {
                return ((string)(this["General_Profile"]));
            }
            set {
                this["General_Profile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Emulator_Width {
            get {
                return ((int)(this["Emulator_Width"]));
            }
            set {
                this["Emulator_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Emulator_Height {
            get {
                return ((int)(this["Emulator_Height"]));
            }
            set {
                this["Emulator_Height"] = value;
            }
        }
    }
}
