//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonicNextModManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SonicNextModManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Category&quot;: &quot;Sonic &apos;06 Mod Manager&quot;,
        ///    &quot;Description&quot;: &quot;Credits_SonicNextModManager&quot;,
        ///    &quot;GitHub&quot;: &quot;https://github.com/Big-Endian-32/SonicNextModManager&quot;,
        ///    &quot;IsExpanded&quot;: true,
        ///    &quot;Contributors&quot;: [
        ///      {
        ///        &quot;Name&quot;: &quot;Hyper&quot;,
        ///        &quot;Description&quot;: &quot;Lead developer, designer and reverse-engineer&quot;,
        ///        &quot;URL&quot;: &quot;https://github.com/HyperBE32&quot;
        ///      },
        ///      {
        ///        &quot;Name&quot;: &quot;Sajid&quot;,
        ///        &quot;Description&quot;: &quot;GitHub API&quot;,
        ///        &quot;URL&quot;: &quot;https://github.com/Sajidur78&quot;
        ///      } [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Game_Executable_360 {
            get {
                object obj = ResourceManager.GetObject("Game_Executable_360", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Game_Executable_PS3 {
            get {
                object obj = ResourceManager.GetObject("Game_Executable_PS3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SonicNextModManager.
        /// </summary>
        internal static string GitHub_Repository {
            get {
                return ResourceManager.GetString("GitHub_Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big-Endian-32.
        /// </summary>
        internal static string GitHub_User {
            get {
                return ResourceManager.GetString("GitHub_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozilla/5.0 (compatible; SonicNextModManager).
        /// </summary>
        internal static string Web_UserAgent {
            get {
                return ResourceManager.GetString("Web_UserAgent", resourceCulture);
            }
        }
    }
}
